version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: taskchallenge_mysql
    environment:
      MYSQL_DATABASE: task_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass123
      MYSQL_ROOT_PASSWORD: rootpass123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "taskuser", "-ptaskpass123"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Task Challenge API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: taskchallenge_api
    environment:
      DATABASE_URL: mysql+pymysql://taskuser:taskpass123@mysql:3306/task_db
      SECRET_KEY: kJ8x9mN2pQ5rT8vW1yZ4aC7bF9hK2nP6sU9xB4eH7jL0mQ3tV6yC8fG1kN4qR7uX
      DEBUG: "true"
      LOG_LEVEL: INFO
      LOG_FORMAT: text
      RUN_MIGRATIONS: "true"
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: taskchallenge_network 